name: pixmotion
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.24
  - pillow>=10
  - sqlalchemy>=2
  - requests>=2
  - pip:
      - PyQt6>=6.7
      - opencv-python>=4.9
